const Icons = {
  padlock: require('./padlock.png'),
  movie: require('./Group.png'),
  hamburger: require('./hamburger_icon.png'),
  home: require('../icons/BottomBarIcons/home.png'),
  favorite: require('../icons/BottomBarIcons/favorite.png'),
  profile: require('../icons/BottomBarIcons/profile.png'),
  search: require('../icons/BottomBarIcons/search.png'),
  searchBar: require('../icons/SearchBarIcons/Search.png'),
  voice: require('../icons/SearchBarIcons/Voice.png'),
  leftArrowIcon: require('../icons/MovieView/left_arrow_icon.png'),
  favorites: require('../icons/MovieView/favorites.png'),
  hearth: require('../icons/MovieView/hearth.png'),
  star: require('../icons/MovieView/star.png'),
  download: require('../icons/MovieView/download.png'),
  play: require('../icons/MovieView/play.png'),
  rate: require('../icons/MovieView/rate.png'),
  plus: require('../icons/MovieView/plus.png'),
  right_back: require('../icons/MovieView/right_back.png'),
  searchFavorite: require('../icons/SearchBarView/favorite_icon.png'),
  filter: require('../icons/SearchBarView/filter.png'),
  playVideo: require('../icons/Trailers/play_video.png'),
  starFilled: require('../icons/Trailers/starFilled.png'),
  starEmpty: require('../icons/Trailers/starEmpty.png'),
};

export default Icons;
